### PR TITLE
Make it v0.12 compliant

### PR DESCRIPTION
**Pull request by ziporah**
You cannot use this verification method anymore in v0.12. Instead I switched to a local-exec provisioner that will fail and put up an error message of incorrect restart policy as suggested [here](https://github.com/hashicorp/terraform/issues/15469)
The valildation of the variables also fails, since the variable definitions have changed. I used type any instead of map, since the validator expects the map to be exactly the same as defined in the variables.tf file.
Changing it to any, still allows the free-defined map to be used, so you can template the spec file in the main code. see [docs](https://www.terraform.io/upgrade-guides/0-12.html#type-constraints-on-variables)

### CODE REVIEW

**Comment by BramCeulemans** [comment]
Any updates on this? @ludoo

**Comment by ludoo** [comment]
@BramCeulemans I only authored the Container Optimized OS submodules, guess you'll have to wait for one of the original authors to chime in. :)

**Comment by ziporah** [comment]
is there a possibility to see the output of the checks ? I'm unable to login to the concourse, and that would help a lot. I've tested the make test_integration local, and it succeeds, but sometimes the hello-world container takes to long to spin up and the verification fails. Running the second time with the same config works .... The managed-instance-group-local example can't be validated since the mig module is also incompatible with v0.12.0. Not sure how to handle this now, so I disabled the test for now, as it is not relevant to this module.

**Comment by aaron-lane** [comment]
@ziporah unfortunately, our CI system is not open to the public at present. I'm adjusting the pipeline to source the correct Docker images as it does not depend on the Makefile for that information. Can you please revert https://github.com/terraform-google-modules/terraform-google-container-vm/pull/26/commits/3873a61ad5634ab0810165be598753cf35c81985 so we can understand what is failing?

**Comment by ziporah** [comment]
Reverted ... good luck !

**Comment by ziporah** [comment]
any progress on the integration test with the mig module ?

**Comment by aaron-lane** [comment]
@ziporah can you please rebase your branch against aaron-lane-0.12?

**Comment by ziporah** [comment]
I believe I rebased, but the lint-tests are still failing.
https://gist.github.com/ziporah/5e173ef52c0922ffbc861d7865334576

**Comment by morgante** [comment]
@aaron-lane Looks like we need to make a 0.12 version of the lint image available as well.

**Comment by aaron-lane** [comment]
Version 2.0.0 of the lint image should Terraform 0.12. I wonder if failure is due to the sourced modules in the example being incompatible with Terraform 0.12. We may need to completely axe the example until a 0.12 variant is developed.

**Comment by BramCeulemans** [comment]
Any updates on this? I would quite like to update to Terraform 0.12

**Comment by morgante** [comment]
Terraform 0.12 compatibility was added via #27.

**Pull request closed without merging**
