### PR TITLE
fix: restart policy kills konlet-startup container fix for the value Never

### PR DESCRIPTION
**Pull request by abhisek00**
Fix for the  issue #79

### CODE REVIEW

**Comment by comment-bot-dev** [comment]
Thanks for the PR! 🚀<br/>✅ Lint checks have passed.

**Comment by abhisek00** [comment]
@bharathkkb - Would you please check why other triggers are still pending

**Review by apeabody — APPROVED** [review]
@abhisek00 - Thanks for the contribution!

**Pull request merged**
